"""
nhse_verification.py

Numerical verification code used for the revised "Quantum Resource Theory for the
Reciprocity-Breaking Sector of the Non-Hermitian Skin Effect" paper.

What this script does, in order:

  1. Implements the Julia unitary dilation of a (sub-normalized) non-Hermitian
     propagator K = U_H(t)/sqrt(kappa), and computes the exact half-diamond-norm
     channel asymmetry A_diamond(N) = (1/2)||N - N^rev||_diamond for unitary
     conjugation channels, using the closed-form "minimal covering arc" formula
     for unitary-channel discrimination (Acin, PRL 87, 177901 (2001)).

  2. Sanity-checks that formula against the paper's own closed-form two-site
     Hatano-Nelson result (Theorem 7 / "gauge-amplification no-go"):
         A_diamond(g) = sqrt(1 - c(g)^2),
         c(g) = u^2 + sqrt((1-u^2 e^{2g})(1-u^2 e^{-2g})),  u = kappa^{-1/2}.

  3. Builds open-boundary Hatano-Nelson chains H_g of increasing length L,
     confirms that ||U_{H_g}(t)||_op saturates as L grows (so a single
     normalization kappa can be chosen uniformly in L), and computes the
     "windowed" channel asymmetry A_diamond(N_H,t^(w)) for windows of width
     w = 2..30, showing convergence to a bulk value a_infinity.

  4. Fits the exponential convergence rate of the windowed values to the bulk
     limit (the quasi-locality decay rate mu quoted in the paper's Lemma on
     windowed truncation error).

  5. Compares, for chains of total length L tiled into non-overlapping windows
     of width w, the block-additive extensive sum E_diamond = floor(L/w) * a_w
     (grows linearly in L, by construction) against the GLOBAL diamond-norm
     asymmetry of the whole L-site chain treated as one channel (which
     saturates, per Prop. 3 of the paper).

  6. Produces the two-panel figure "fig_windowed_convergence.pdf/.png" used in
     the paper (windowed A_diamond vs w, and the exponential residual fit).

Requires: numpy, scipy, matplotlib.
Run with:  python3 nhse_verification.py
"""

import numpy as np
from scipy.linalg import expm

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


# ----------------------------------------------------------------------
# 1. Julia dilation and exact diamond-norm channel asymmetry
# ----------------------------------------------------------------------

def sqrtm_psd(A):
    """Positive-semidefinite matrix square root via eigendecomposition."""
    w, v = np.linalg.eigh((A + A.conj().T) / 2)
    w = np.clip(w, 0, None)
    return (v * np.sqrt(w)) @ v.conj().T


def U_from_H(H, t):
    """Non-Hermitian propagator U_H(t) = exp(-i H t)."""
    return expm(-1j * H * t)


def julia_from_H(H, t, kappa):
    """
    Build the Julia-dilated unitary

        Utilde_K = [[K, D_{K^dagger}], [D_K, -K^dagger]]

    for the sub-normalized contraction K = U_H(t) / sqrt(kappa).
    """
    K = U_from_H(H, t) / np.sqrt(kappa)
    d = K.shape[0]
    Kd = K.conj().T
    DK = sqrtm_psd(np.eye(d) - Kd @ K)
    DKd = sqrtm_psd(np.eye(d) - K @ Kd)
    top = np.hstack([K, DKd])
    bot = np.hstack([DK, -Kd])
    return np.vstack([top, bot])


def half_diamond_A(Utilde):
    """
    A_diamond = (1/2)||N - N^rev||_diamond for the unitary conjugation channel
    N(X) = Utilde X Utilde^dagger, where N^rev is generated by the *transpose*
    Utilde^T (transpose in the fixed real-space basis).

    Uses the exact unitary-channel discrimination formula: writing
    W = Utilde^dagger Utilde^T, if the eigenvalue phases of W lie within a
    minimal covering arc of half-angle phi <= pi/2, then A_diamond = sin(phi);
    A_diamond saturates at 1 once the minimal covering arc exceeds pi.
    (Acin, PRL 87, 177901 (2001).)
    """
    W = Utilde.conj().T @ Utilde.T
    ev = np.linalg.eigvals(W)
    ang = np.sort(np.angle(ev) % (2 * np.pi))
    gaps = np.diff(np.concatenate([ang, [ang[0] + 2 * np.pi]]))
    maxgap = np.max(gaps)
    enclosing_arc = 2 * np.pi - maxgap
    if enclosing_arc > np.pi:
        return 1.0
    phi = enclosing_arc / 2.0
    return np.sin(phi)


# ----------------------------------------------------------------------
# 2. Sanity check against the paper's closed-form Theorem 7
# ----------------------------------------------------------------------

def two_site_H(g, t0=1.0):
    """Two-site Hatano-Nelson calibration Hamiltonian."""
    return t0 * np.array([[0, np.exp(g)], [np.exp(-g), 0]])


def closed_form_A(g, u):
    """Exact closed form from Theorem 7 (gauge-amplification no-go)."""
    a = np.sqrt(1 - u**2 * np.exp(-2 * g))
    b = np.sqrt(1 - u**2 * np.exp(2 * g))
    c = u**2 + a * b
    return np.sqrt(max(0.0, 1 - c**2))


def run_sanity_check():
    t0 = 1.0
    tau_star = np.pi / (2 * t0)
    gmax = 1.5
    kappa = np.exp(2 * gmax) * 1.2  # kappa > e^{2 g_max}, an admissible normalization
    u = kappa**-0.5

    print("=" * 70)
    print("Sanity check: numerical A_diamond vs. closed-form Theorem 7")
    print("=" * 70)
    print(f"{'g':>6} {'numeric A_diamond':>20} {'closed-form (Thm 7)':>22}")
    for g in [0.1, 0.3, 0.6, 0.9, 1.2, 1.5]:
        H = two_site_H(g)
        Ut = julia_from_H(H, tau_star, kappa)
        Anum = half_diamond_A(Ut)
        Acf = closed_form_A(g, u)
        print(f"{g:6.2f} {Anum:20.6f} {Acf:22.6f}")
    print()


# ----------------------------------------------------------------------
# 3. Windowed / extensive numerics for the coupled Hatano-Nelson chain
# ----------------------------------------------------------------------

def hn_chain(L, g, t0=1.0):
    """Open-boundary Hatano-Nelson chain Hamiltonian of length L."""
    H = np.zeros((L, L), dtype=complex)
    for n in range(L - 1):
        H[n, n + 1] = t0 * np.exp(g)
        H[n + 1, n] = t0 * np.exp(-g)
    return H


def run_windowed_analysis(g=0.5, t_op=0.35, t0=1.0,
                           widths=(2, 3, 4, 6, 8, 10, 14, 18, 24, 30)):
    print("=" * 70)
    print("Windowed local restriction: convergence to a bulk value as w grows")
    print("=" * 70)

    # Step 1: check that ||U_H(t)||_op saturates as L grows (uniform normalization)
    print(f"{'L':>4} {'||U_H(t)||_op':>16}")
    norms = []
    for L in [2, 4, 6, 8, 10, 14, 18, 24, 30]:
        H = hn_chain(L, g, t0)
        nrm = np.linalg.norm(U_from_H(H, t_op), 2)
        norms.append(nrm)
        print(f"{L:4d} {nrm:16.6f}")

    kappa = (1.05 * max(norms))**2
    print(f"\nchosen uniform kappa = {kappa:.6f}\n")

    # Step 2: windowed A_diamond as a function of window width w
    print(f"{'w':>4} {'A_diamond(window)':>20}")
    vals = []
    for w in widths:
        H = hn_chain(w, g, t0)
        Ut = julia_from_H(H, t_op, kappa)
        A = half_diamond_A(Ut)
        vals.append((w, A))
        print(f"{w:4d} {A:20.6f}")
    print()

    return kappa, vals


def fit_exponential_convergence(vals):
    print("=" * 70)
    print("Exponential (quasi-locality) convergence-rate fit")
    print("=" * 70)
    ws = np.array([w for w, _ in vals])
    As = np.array([a for _, a in vals])
    a_inf_est = As[-1]  # best available numerical estimate of the bulk limit
    resid = a_inf_est - As[:-1]
    ws2 = ws[:-1]
    mask = resid > 1e-6
    logres = np.log(resid[mask])
    wfit = ws2[mask]
    Amat = np.vstack([wfit, np.ones_like(wfit)]).T
    slope, intercept = np.linalg.lstsq(Amat, logres, rcond=None)[0]
    mu = -slope
    print(f"bulk value estimate  a_infinity ~ {a_inf_est:.6f}")
    print(f"fitted decay rate    mu         ~ {mu:.6f}")
    print("(residual a_infinity - a_w ~ C * exp(-mu * w))\n")
    return a_inf_est, mu


def run_extensive_vs_global(g=0.5, t_op=0.35, t0=1.0, kappa=None, w=8,
                             totals=(8, 16, 24, 40, 60, 100)):
    print("=" * 70)
    print("Extensive block-additive sum vs. bounded global diamond norm")
    print("=" * 70)

    H_w = hn_chain(w, g, t0)
    a_w = half_diamond_A(julia_from_H(H_w, t_op, kappa))
    print(f"window width w = {w}, local bond/window value a_w = {a_w:.6f}\n")

    print(f"{'L_total':>8} {'#windows':>9} {'E_diamond=floor(L/w)*a_w':>26} "
          f"{'global A_diamond(whole chain)':>30}")
    rows = []
    for Lt in totals:
        nwin = Lt // w
        ext = nwin * a_w
        if Lt <= 60:  # global diagonalization gets expensive; cap it
            H = hn_chain(Lt, g, t0)
            Aglob = half_diamond_A(julia_from_H(H, t_op, kappa))
        else:
            Aglob = float("nan")
        rows.append((Lt, nwin, ext, Aglob))
        glob_str = f"{Aglob:.6f}" if not np.isnan(Aglob) else "---"
        print(f"{Lt:8d} {nwin:9d} {ext:26.3f} {glob_str:>30}")
    print()
    return a_w, rows


# ----------------------------------------------------------------------
# 4. Figure generation (reproduces fig_windowed_convergence.pdf/.png)
# ----------------------------------------------------------------------

def make_figure(vals, a_inf, mu, outbase="fig_windowed_convergence"):
    w = np.array([v[0] for v in vals])
    a = np.array([v[1] for v in vals])

    fig, axes = plt.subplots(1, 2, figsize=(9, 3.6))

    ax = axes[0]
    ax.plot(w, a, 'o-', color='#1f4e79',
            label=r'$A_\diamond$ of $w$-site window (numerical)')
    ax.axhline(a_inf, ls='--', color='gray', label=r'bulk limit $a_\infty$')
    ax.set_xlabel('window width w (sites)')
    ax.set_ylabel(r'$A_\diamond$')
    ax.set_title('(a) windowed channel asymmetry converges')
    ax.legend(fontsize=8)

    ax = axes[1]
    resid = a_inf - a
    mask = resid > 1e-6
    ax.semilogy(w[mask], resid[mask], 'o', color='#a6320a',
                label='numeric residual')
    wf = np.linspace(w[mask].min(), w[mask].max(), 50)
    ax.semilogy(
        wf, resid[mask][0] * np.exp(-mu * (wf - w[mask][0])), '--',
        color='gray', label=fr'fit $\propto e^{{-\mu w}}$, $\mu\approx{mu:.2f}$'
    )
    ax.set_xlabel('window width w (sites)')
    ax.set_ylabel(r'$a_\infty - A_\diamond^{(w)}$')
    ax.set_title('(b) exponential (quasi-local) convergence')
    ax.legend(fontsize=8)

    plt.tight_layout()
    plt.savefig(outbase + ".pdf")
    plt.savefig(outbase + ".png", dpi=150)
    print(f"Saved {outbase}.pdf and {outbase}.png")


# ----------------------------------------------------------------------
# main
# ----------------------------------------------------------------------

if __name__ == "__main__":
    run_sanity_check()

    kappa, vals = run_windowed_analysis()
    a_inf, mu = fit_exponential_convergence(vals)
    run_extensive_vs_global(kappa=kappa, w=8)

    make_figure(vals, a_inf, mu)
